# RTPQueue Configuration
default_world: world

messages:
  prefix: "&e[RTP Queue] &7 >> "
  join_queue: "&aYou have joined the RTP queue."
  leave_queue: "&cYou have left the RTP queue."
  config_reloaded: "&eConfiguration reloaded."
  teleport_success: "&6Teleported successfully!"
  action_bar_join_message: "&a&lIN QUEUE"
  action_bar_leave_message: "&c&lLEFT QUEUE"
  action_bar_teleport_message: "&6&lTELEPORTED!"
  queue_announcement: "&e%player% is looking for a 1v1! &a&l[CLICK TO JOIN]"
  queue_full: "&cQueue is full! Try again later."
  teleport_countdown: "&eTeleporting in %time% seconds!"
  already_queue: "&aYou are already in the queue!"

sounds:
  teleport: "ENTITY_ENDERMAN_TELEPORT"
  volume: 1.0
  pitch: 1.0

teleport:
  max_attempts: 5
  min_x: -1000
  max_x: 1000
  min_z: -1000
  max_z: 1000

safe_location_checks:
  - GRASS_BLOCK
  - DIRT
  - STONE
  - COBBLESTONE