#########################################################################################
#                                                                                       #
# DeluxeRTPQueue, a free resource by Swagger Studio @                                   #
#                                                                                       #
# Support: https://minecraftinfinity.com/discord                                        #
# Tutorial: Coming very Soon at YT https://bit.ly/kanhaiyaswagger                       #
# Sponsored by: https://swagger.cloud/ BEST Hosting + User Friendly + Trustable         #
#                                                                                       #
# You are editing the config.yml file of DeluxeRTPQueue.                                #
#                                                                                       #
#########################################################################################
# Enable or disable debug logging (set to true to see detailed logs in console)
debug: false

# List of worlds where Random Teleport (RTP) is enabled
rtp_enabled_worlds: [ "world", "world_nether", "world_the_end" ]

# Radius
radius: 1000


# Enables smaller texts.
small-text-enabled: true

# The item used to trigger world selection (can be any valid Material)
selection-item: "SHEARS"

# Whether action bar messages are shown during teleport process
action-bar-enabled: true

# Enables levitation effect during RTP teleport animation
levitation-effect-enabled: true

# Duration of the levitation effect in seconds
levitation-effect-duration: 5

# Minimum distance from other players where the player should be teleported
spawn-spacing: 5

# Radius (in blocks) of the safe search area around the target teleport location
circle-radius: 10

# Strength of the levitation effect (0 = Levitation I)
levitation-effect-amplifier: 0

# If true, teleport target will be adjusted to face a safe/flat direction
adjust-face: true

# Enable or disable sound effects when teleporting
sounds-enabled: true

# List of blocks that are not allowed at or near the teleport destination
restricted-blocks:
  - WATER
  - LAVA
